### ISSUE TITLE
Nerozumiem tomuto vytvaraniu novych items a podobne aj heroes

### ISSUE THREAD

**Issue by katarinaHrab** [SimonCanecky/Tour-of-Heroes#1]
https://github.com/SimonCanecky/Tour-of-Heroes/blob/aac197a62c01e9838861f3106a7af463b36e8b19/src/app/item-form/item-form.component.ts#L24

Btw, metody sa pisu s malym zaciatocnym pismenkom a akosi nechapem tuto ts classu. Aj ti to vytvara z tych hodnot ake zadas vo formulari, ci iba tieto natvrdo zadane v modeli?

**Comment by SimonCanecky** [comment]
Áno ako predvolené zobrazí tie natvrdo dané hodnoty ale dajú sa upraviť a
vytvorí to podľa hodnôt ktoré zadáme.

Dňa po 8. 3. 2021, 14:15 Katarína Hrabovská <notifications@github.com>
napísal(a):

**Comment by katarinaHrab** [comment]
Aha, dobre. Potom fajn :)
Super, ze si dokoncil vsetky cvicenia.
